"""create calendar_block and section

Revision ID: 9f2ef01e38f8
Revises: e90cf37b93ac
Create Date: 2025-12-14 18:13:11.603201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2ef01e38f8'
down_revision: Union[str, Sequence[str], None] = 'e90cf37b93ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lessons', sa.Column('section_id', sa.Integer(), nullable=False))
    op.add_column('lessons', sa.Column('auditory', sa.String(), nullable=False))


    op.execute("""
        ALTER TABLE lessons
        ALTER COLUMN day_of_week TYPE INTEGER
        USING CASE day_of_week
            WHEN 'Monday' THEN 0
            WHEN 'Tuesday' THEN 1
            WHEN 'Wednesday' THEN 2
            WHEN 'Thursday' THEN 3
            WHEN 'Friday' THEN 4
            WHEN 'Saturday' THEN 5
            WHEN 'Sunday' THEN 6
        END
    """)

    op.alter_column('lessons', 'teacher',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'lessons', 'sections', ['section_id'], ['id'])
    op.drop_column('lessons', 'room')
    op.drop_column('lessons', 'week_type')
    op.add_column('overrides', sa.Column('section_id', sa.Integer(), nullable=True))
    op.add_column('overrides', sa.Column('new_auditory', sa.String(), nullable=True))
    op.create_foreign_key(None, 'overrides', 'sections', ['section_id'], ['id'])
    op.drop_column('overrides', 'new_room')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overrides', sa.Column('new_room', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'overrides', type_='foreignkey')
    op.drop_column('overrides', 'new_auditory')
    op.drop_column('overrides', 'section_id')
    op.add_column('lessons', sa.Column('week_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('room', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lessons', type_='foreignkey')
    op.alter_column('lessons', 'teacher',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
    op.execute("""
        ALTER TABLE lessons
        ALTER COLUMN day_of_week TYPE VARCHAR
        USING CASE day_of_week
            WHEN 0 THEN 'Monday'
            WHEN 1 THEN 'Tuesday'
            WHEN 2 THEN 'Wednesday'
            WHEN 3 THEN 'Thursday'
            WHEN 4 THEN 'Friday'
            WHEN 5 THEN 'Saturday'
            WHEN 6 THEN 'Sunday'
        END
    """)
    
    op.drop_column('lessons', 'auditory')
    op.drop_column('lessons', 'section_id')
    op.drop_table('calendar_blocks')
    op.drop_table('sections')
    # ### end Alembic commands ###
