"""create lessons and overrides

Revision ID: e90cf37b93ac
Revises: 
Create Date: 2025-12-14 16:00:59.002975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90cf37b93ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_type', sa.String(length=10), nullable=True),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('time_start', sa.Time(), nullable=False),
    sa.Column('time_end', sa.Time(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('lesson_type', sa.String(), nullable=False),
    sa.Column('teacher', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('groups', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('new_time_start', sa.Time(), nullable=True),
    sa.Column('new_time_end', sa.Time(), nullable=True),
    sa.Column('new_room', sa.String(), nullable=True),
    sa.Column('new_teacher', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overrides')
    op.drop_table('lessons')
    # ### end Alembic commands ###
